#! /usr/bin/perl -i.orig
#
#
# ++Copyright BAKA++
#
# Copyright © 2001-2008 The Authors. All rights reserved.
#
# This source code is licensed to you under the terms of the file
# LICENSE.TXT in this release for further details.
#
# Send e-mail to <projectbaka@baka.org> for further information.
#
# - -Copyright BAKA- -
#
#
sub BEGIN
{
  $FIRST="## BEGIN BKSTANDARD MAKEFILE";
  $MIDDLE=<<'EOF';
-include ./Make.preinclude
-include $(GROUPTOP)/Make.preinclude
-include $(GROUPTOP)/$(PKGTOP)/Make.preinclude
include $(GROUPTOP)/$(PKGTOP)/bkmk/Make.include
-include $(GROUPTOP)/$(PKGTOP)/Make.include
-include $(GROUPTOP)/Make.include
-include ./Make.include
EOF
  $LAST="## END BKSTANDARD MAKEFILE";
}

while (<>)
{
  if ($. == 1)
    {
print STDERR "Looking at $ARGV\n" ;
      $state = 0;
    }
  if ($state == 2)
    {
      print;
    }
  if ($state == 1)
    {
      $state = 2 if /^$LAST/;
    }
  if ($state == 0)
    {
      if (/^$FIRST/)
	{
print STDERR "FOUND $ARGV\n";
	  $state = 1;
	  print "$FIRST\n$MIDDLE$LAST\n";
	}
      else
	{
	  print;
	}
    }
  close ARGV if eof;              # Reset $.
}
